# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b93f21d0f7b55b8a3bdada0c5ecde894f6b5325d9028cdf277084192f592ff966f6d3bb1d362365600677c37d8d83d5b35253cbd1a3d2d0c29300eeabe190459

test:
  secret_key_base: 6a2b93de9dbf77e19c4b5b20b2b162bbb7c1d15b654cb7cda253ba0d088d0bdaf0f6e4338aa85ce5dd0980ed53fa10c2ff4008c69f867424bca5c7969c0cc8ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
